Feature/task1
tssvett/MediaSoftTestTask pull request #2
Opened 2024-04-18 12:20 UTC by tssvett

The first homework is completed. A simple and optimized shader has been made, its own annotation for measuring time has been added, and an aspect for measuring time @Transactional has been added.

2024-04-21 09:08 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "Feature/task1". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 09:23 UTC, GUR-ok requested changes

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/App.java
> +import org.springframework.scheduling.annotation.EnableScheduling;
Зачем это в этом классе? у тебя EnableScheduling  в конфигурациях? Проверьв се классы на неиспользуемые импорты.

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/annotation/aspects/NonTransactionalAspect.java
> +            System.out.println("@MeasureWorkingTime execution time of " + className +" Method name " + methodName +" is " + stopWatch.getTotalTimeMillis() + " ms");
sout не используем в боевом закоммиченном коде. сделать через логирование

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/annotation/aspects/TransactionAspect.java
> +        System.out.println("Starting @Transactional time measurement for " + className +" Method name " + methodName);
sout поменять на логирование

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/model/WarehouseGood.java
> +@Data
Data наоборот не используем в entity

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/SimpleGoodsPriceSchedulerImpl.java
> +    private WarehouseGoodRepository warehouseGoodRepository;
Инжектим через конструктор.. В первую очередь так нам проще создавать тестируемый класс в юнит тестах

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +import java.sql.*;
Давай избегать схлопнутых импортов

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +    private DataSource dataSource;
инжект через констурктор

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +        Connection connection = dataSource.getConnection();
connection и writer вынести в ресурсы трай-с-ресурсами. тогда клозить не нужно будет вручную

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +        PreparedStatement statement = connection.prepareStatement("SELECT * FROM warehouse_goods");
SELECT * FROM warehouse_goods FOR UPDATE

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +        PreparedStatement statement = connection.prepareStatement("SELECT * FROM warehouse_goods");
Селект мы делаем 1 раз и з параметром. Наверно лучше простым стейтментом

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +            WarehouseGood updatedGood = WarehouseGood.builder()
Так по памяти не просядем, создавая каждый раз целый объект? мы же меняем просто цену.
И в  квери нужна только цена и айди String query = "UPDATE warehouse_goods SET price = ? WHERE id = ?";
Не нужно создавать целый объект. Передавай в приватный метод только айди и цену

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +
К connection не выставляется autocommit(false). Он будет по дефолту коммитить каждый стейтмент. Нужно вручную управлять коммитом и роллбэком.  Когда будет try-catch, роллбэк будет в catch.

2024-04-21 09:23 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +
форматирование

2024-04-22 18:29 UTC, tssvett commented on src/main/java/com/warehousesystem/app/scheduling/impl/OptimizedGoodsPriceSchedulerImpl.java
> +
Поправил ваши замечания, посмотрите пожалуйста.

2024-04-25 15:43 UTC, GUR-ok commented
зря в мр воткнул техдолг с исключениям. нужно делать отдельным мр! Но апрув прожму. сейчас ничего не меняй. В будущем давай так не делать

2024-04-25 15:43 UTC, GUR-ok commented
нужен фикс конфликтов

2024-04-25 15:44 UTC, GUR-ok approved these changes
после фикса конфликтов удостоверься, что все собирается и запускается

2024-05-01 09:34 UTC, GUR-ok approved these changes
можно мержить. со сквошем

2024-06-07 11:07 UTC, merged