Task2 : Criterial Search
tssvett/MediaSoftTestTask pull request #4
Opened 2024-04-25 19:11 UTC by tssvett

2024-04-27 07:07 UTC, GUR-ok requested changes

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/controller/WarehouseController.java
> +    @GetMapping("/sortBy")
/sortBy не ок. /search

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/criteria/BigDecimalSearchCriteria.java
> +    private PredicateStrategy<BigDecimal> strategy = new BigDecimalPredicateStrategy();
Давай сделаем статическим, чтобы не создавалась стратегия каждый раз при создании критерия

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/criteria/SearchCriteria.java
> +
Почему так много пустых строк? Следи за форматированием плз

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/criteria/SearchCriteria.java
> +        //@JsonSubTypes(Type = UUIDSearchCriteria.class, name = "id"),
Не должно быть закомменченного кода. Почему убрал?

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/criteria/UUIDSearchCriteria.java
> +    private String operation;
Почему тут не енум? Подправь класс енума, чтобы десериализовалось сразу в енум а не строку

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/criteria/UUIDSearchCriteria.java
> +    public String getField() {
Почему не пользуешь ломбоковский Data Builder или хотя бы Setter?

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/criteria/StringSearchCriteria.java
> +    @Getter
Тут почему-то аннотацией геттер создал, а потом вручную.. используй ломбок

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/strategy/PredicateStrategy.java
> +
Форматирование

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/service/impl/WarehouseGoodServiceImpl.java
> +            Predicate predicate = cb.conjunction();
Вместо анонимного класса давай вынесем в  отдельный public class WarehouseGoodSpecification implements Specification-WarehouseGood-, который хранит в себе список всех критериев и собирает предикаты. WarehouseGood кстати очень нераспространенное название для обозначения сущности "товар" )

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/service/impl/WarehouseGoodServiceImpl.java
> +        PageRequest pageRequest = PageRequest.of(pageNumber, size, pageable.getSort());
Не понял, зачем здесь создавать  новый PageRequest pageRequest, если в репозиторий можно сразу передать pageable, который есть во входных аргументах метода

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/service/impl/WarehouseGoodServiceImpl.java
> +
после ретурн не нужно пустую строку. а вот сам ретурн лучше отделять пустой строкой от кода выше него

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/enums/OperationType.java
> +        case "LIKE", "~" -> OperationType.LIKE;
LIKE можно взять из названия же самого экземпляра енума.. Еще у енумов можно добавлять поля. сделай так
```
package com.crudshop.demo.service.search.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```

Есть еще лаконичней, когда через jsonALias

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/search/strategy/BigDecimalPredicateStrategy.java
> +
лишние пустые строки

2024-04-27 07:07 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/controller/WarehouseController.java
> +    @GetMapping("/sortBy")
Грубейшая ошибка: у тебя GET метод и ты передаешь тело запроса. так нельзя

2024-05-04 11:20 UTC, GUR-ok commented
конфликты

2024-06-07 17:21 UTC, tssvett commented on src/main/java/com/warehousesystem/app/search/strategy/BigDecimalPredicateStrategy.java
> +
Поправил замечания, посмотрите пожалуйста

2024-06-08 09:11 UTC, GUR-ok approved these changes
Одно замечание оставил. По самой задаче ок. Как поправишь, можно подмержить со сквошем

2024-06-08 09:11 UTC, GUR-ok commented on src/main/java/com/warehousesystem/app/controller/WarehouseController.java
> +    public ResponseEntity<WarehouseGoodFullDto> createGood(@Valid @RequestBody WarehouseGoodUpdateDto warehouseGood) throws SQLUniqueException {
Для create и для update не хорошо общую дто использовать. У тебя метод createGood, а дто принимает WarehouseGoodUpdateDto

2024-06-13 09:21 UTC, merged